### ISSUE TITLE
Having some trouble building...

### ISSUE THREAD

**Issue by pmetzger** [smolkaj/ocaml-parsing#1]
Howdy! I'm having some trouble building. Perhaps it is just a question of not having the right packages installed via OPAM.

First of all, the build begins with this:

> oasis setup-clean
> oasis setup
> W: Cannot find source file matching module 'My_Tokens' in library parser.
> W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".

Second, at the end, I get this, which seems to be the bad part:

> + /Users/perry/.opam/4.05.0/bin/ocamlfind ocamldep -package sedlex -package ppx_import -package core -package compiler-libs.common -package MenhirLib -package ppx_deriving,ppx_deriving.eq,ppx_deriving.enum,ppx_deriving.show,ppx_jane -modules src/My_Lexer.mli > src/My_Lexer.mli.depends
> File "src/My_Lexer.mli", line 1, characters 58-67:
> Error: Cannot locate deriver enumerate
> Command exited with code 2.
> Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
> E: Failure("Command ''/Users/perry/.opam/4.05.0/bin/ocamlbuild' src/parser.cma test.byte -use-ocamlfind -use-menhir -cflags -w,@5+8@11@12-40,-short-paths -package ppx_deriving,ppx_deriving.eq,ppx_deriving.enum,ppx_deriving.show,ppx_jane -tag debug -tag tests' terminated with error code 10")
> make[1]: *** [all] Error 1
> make: *** [default] Error 2

**Comment by pmetzger** [comment]
I should perhaps note that I have all of

> `menhir sedlex core oasis ppx_import ppx_deriving`

installed already, and those are the only dependencies listed in the readme.

**Comment by smolkaj** [comment]
The code was a bit outdated, so I pushed some updates. You're also missing the dependency `ppx_enumerate`, which I forgot to mention in the README (now fixed). Let me know if it works now.

**Comment by pmetzger** [comment]
It does seem to compile now, though there are still a bunch of warnings along the way. Are they to be expected? I can reproduce them here if you like.

**Comment by smolkaj** [comment]
Is this the error you're seeing?:
```
+ /Users/steffen/.opam/4.05.0/bin/ocamlfind ocamldoc -dump src/My_Lexer.odoc -I +threads -package threads -package sedlex -package ppx_import -package core -package compiler-libs.common -package MenhirLib -I src src/My_Lexer.mli
ocamlfind: [WARNING] Package `threads' signals error: Missing -thread or -vmthread switch
```
Note that it is thrown while generating the documentation, not while building. So you can safely ignore it.

By the way, currently this package relies on `oasis` for building. Unfortunately oasis is not very robust and suffers from issues like the above. Recently Jane Street's jbuilder has gained in popularity, and this is becoming the defacto default for building OCaml projects. Jbuilder is much more robust, and also much (about 10x) faster!

So I may update this package to use jbuilder instead of oasis to avoid such issues in the future.

**Comment by smolkaj** [comment]
@pmetzger: I switched from oasis to jbuilder. Let me know if this works

**Comment by pmetzger** [comment]
I'll try jbuilder out.

**Comment by smolkaj** [comment]
5560cfe7e5ea693fc336643d460dd6b750a85585 fixes this issue.
