### ISSUE TITLE
Please provide ability to compile to js_of_ocaml if possible

### ISSUE THREAD

**Issue by loxs** [smolkaj/ocaml-parsing#4]
Is it possible co compile to js_of_ocaml with this setup?
I know Core is incompatible with jsoo, but I tried just replacing it with Core_kernel and it seems to compile without problems (to native). Though I can't figure out how to compile to jsoo.

Here is my fork with Core_kernel: https://github.com/loxs/ocaml-parsing

**Comment by smolkaj** [comment]
Hey @loxs. I'm not sure about js_of_ocaml (I haven't used it myself), but it should definitely be possible. Actually, I think the way to go it to use Jane Street's Base instead of core. Base is completely portable. If you want to submit a pull request, I will happily merge it in.

**Comment by loxs** [comment]
Porting to Base was quite easy. 
I'm still an OCaml newbie and struggling with the environment, but this is where I'm at right now.

After porting to Base it compiles to JS with some warnings, the tests work in JS, but the errors are cryptic. Still quite a good start for what I want to do:

```
MacBook-Pro:ocaml-parsing loxs$ jbuilder build test/test.bc.js
 js_of_ocaml test/test.bc.js
There are some missing primitives
Dummy implementations (raising 'Failure' exception) will be used if they are not available at runtime.
You can prevent the generation of dummy implementations with the commandline option '--disable genprim'
Missing primitives provided by +dynlink.js:
  caml_add_debug_info
  caml_dynlink_add_primitive
  caml_dynlink_get_current_libs
  caml_dynlink_lookup_symbol
  caml_dynlink_open_lib
  caml_register_code_fragment
Missing primitives provided by +toplevel.js:
  caml_get_section_table
  caml_realloc_global
  caml_reify_bytecode
  caml_static_alloc
  caml_terminfo_setup
```

After that you can run the test via node.js:

```
MacBook-Pro:ocaml-parsing loxs$ node _build/default/test/test.bc.js


It's working!

My Tokens:
  Lexer.RPAR
  Lexer.LPAR
  Lexer.EOF

Trying to parse "() ( ()() (()()) )".
-> success!

Trying to parse "( () ()".

/Users/loxs/code/ocaml/ocaml-parsing/_build/default/test/test.bc.js:21009
c=a[2];throw[0,qB,[0,c[1],c[2]]]}throw[0,JW,f[1]]}},a1x=[z,a1w,y(0)],qC=function(g,d,c){var
                                 ^
0,248,Ocaml_parsing__Lexer.ParseError,99,0,2,0,<n/a>,1,0,8,0,<n/a>,1,0,9
```

**Comment by smolkaj** [comment]
Sweet!
