### ISSUE TITLE
Error: Uninterpreted extension 'sedlex.regexp'

### ISSUE THREAD

**Issue by astefano** [smolkaj/ocaml-parsing#6]
Hi, 

i get Error: Uninterpreted extension 'sedlex.regexp' as seen below. menhir is version 20180703. 

Any idea how to fix this?

Thanks,
Lacramioara

====

isar:07:06:16:~/ocaml-parsing$ make
time -p jbuilder build @install
    ocamlopt src/.ocaml_parsing.objs/ocaml_parsing__Lexer.{cmx,o} (exit 2)
(cd _build/default && /home/eugen/.opam/4.06.0/bin/ocamlopt.opt -w -40 -g -I src/.ocaml_parsing.objs -I /home/eugen/.opam/4.06.0/lib/base -I /home/eugen/.opam/4.06.0/lib/base/caml -I /home/eugen/.opam/4.06.0/lib/base/shadow_stdlib -I /home/eugen/.opam/4.06.0/lib/bytes -I /home/eugen/.opam/4.06.0/lib/gen -I /home/eugen/.opam/4.06.0/lib/menhirLib -I /home/eugen/.opam/4.06.0/lib/ocaml/compiler-libs -I /home/eugen/.opam/4.06.0/lib/ppx_deriving -I /home/eugen/.opam/4.06.0/lib/result -I /home/eugen/.opam/4.06.0/lib/sedlex -I /home/eugen/.opam/4.06.0/lib/sexplib0 -I /home/eugen/.opam/4.06.0/lib/stdio -intf-suffix .ml -no-alias-deps -open Ocaml_parsing -o src/.ocaml_parsing.objs/ocaml_parsing__Lexer.cmx -c -impl src/Lexer.pp.ml)
File "src/Lexer.ml", line 42, characters 15-28:
Error: Uninterpreted extension 'sedlex.regexp'.

**Comment by smolkaj** [comment]
Are you still seeing this issue? I can't reproduce it.
It might have to do with all the recent breaking changes in jbuilder/dune. What version do you have? Maybe #9 will fix the issue?

**Comment by astefano** [comment]
Hi, 

yes, it's the same, but this time coming from dune :)

isar:07:23:59:~/ocaml-parsing$ make
dune build
    ocamlopt src/.ocaml_parsing.objs/ocaml_parsing__Lexer.{cmx,o} (exit 2)
(cd _build/default && /home/eugen/.opam/4.06.1/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I src/.ocaml_parsing.objs -I /home/eugen/.opam/4.06.1/lib/base -I /home/eugen/.opam/4.06.1/lib/base/caml -I /home/eugen/.opam/4.06.1/lib/base/shadow_stdlib -I /home/eugen/.opam/4.06.1/lib/bytes -I /home/eugen/.opam/4.06.1/lib/gen -I /home/eugen/.opam/4.06.1/lib/menhirLib -I /home/eugen/.opam/4.06.1/lib/ocaml/compiler-libs -I /home/eugen/.opam/4.06.1/lib/ppx_deriving -I /home/eugen/.opam/4.06.1/lib/result -I /home/eugen/.opam/4.06.1/lib/sedlex -I /home/eugen/.opam/4.06.1/lib/sexplib0 -I /home/eugen/.opam/4.06.1/lib/stdio -intf-suffix .ml -no-alias-deps -opaque -open Ocaml_parsing -o src/.ocaml_parsing.objs/ocaml_parsing__Lexer.cmx -c -impl src/Lexer.pp.ml)
File "src/Lexer.ml", line 42, characters 15-28:
Error: Uninterpreted extension 'sedlex.regexp'.
      ocamlc src/.ocaml_parsing.objs/ocaml_parsing__Lexer.{cmo,cmt} (exit 2)
(cd _build/default && /home/eugen/.opam/4.06.1/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I src/.ocaml_parsing.objs -I /home/eugen/.opam/4.06.1/lib/base -I /home/eugen/.opam/4.06.1/lib/base/caml -I /home/eugen/.opam/4.06.1/lib/base/shadow_stdlib -I /home/eugen/.opam/4.06.1/lib/bytes -I /home/eugen/.opam/4.06.1/lib/gen -I /home/eugen/.opam/4.06.1/lib/menhirLib -I /home/eugen/.opam/4.06.1/lib/ocaml/compiler-libs -I /home/eugen/.opam/4.06.1/lib/ppx_deriving -I /home/eugen/.opam/4.06.1/lib/result -I /home/eugen/.opam/4.06.1/lib/sedlex -I /home/eugen/.opam/4.06.1/lib/sexplib0 -I /home/eugen/.opam/4.06.1/lib/stdio -intf-suffix .ml -no-alias-deps -opaque -open Ocaml_parsing -o src/.ocaml_parsing.objs/ocaml_parsing__Lexer.cmo -c -impl src/Lexer.pp.ml)
File "src/Lexer.ml", line 42, characters 15-28:
Error: Uninterpreted extension 'sedlex.regexp'.
make: *** [build] Error 1

dune is at 1.1.1. and sedlex is at 1.99.3. 
But please feel to close the issue since you can't reproduce it. 

Cheers,
l

**Comment by smolkaj** [comment]
You need sedlex >= 1.99.4 for compatability with jbuilder/dune. I added this constraint to the opam file. Let me know if it works.

**Comment by astefano** [comment]
perfect, thanks, didn't pay attention to this.
